
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="lightland-magic"
version="${file.jarVersion}"
displayName="Lightland Magic"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="lightland.png"
credits="Java, Mojang, and Forge Team"
authors="Hikarishima Team and Dev lcy0x1"
description='''
Light Land is a mod that adds RPG elements to MC
'''
[[dependencies.lightland]]
    modId="lightland-core" 
    mandatory=true 
    versionRange="[{file.jarVersion},{file.jarVersion}]" 
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="forge" 
    mandatory=true 
    versionRange="[36.2,37)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="twilightforest"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="apotheosis"
    mandatory=true
    versionRange="[4.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="patchouli"
    mandatory=true
    versionRange="[53.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="itemstages"
    mandatory=true
    versionRange="[3.0,)"
    ordering="NONE"
    side="BOTH"
